# Generated by Django 6.0.5 on 2026-06-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adm_produto_caixa_estoquista_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm',
            name='cpf',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adm',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
