# Generated by Django 6.0.5 on 2026-06-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adm_cpf_adm_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm',
            name='cpf',
            field=models.CharField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adm',
            name='idade',
            field=models.IntegerField(blank=True, default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caixa',
            name='idade',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquista',
            name='idade',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='idade',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
