# Generated by Django 6.0.5 on 2026-06-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_adm_cpf_alter_adm_idade_alter_caixa_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='usuario',
            field=models.CharField(default='sem_usuario', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquista',
            name='usuario',
            field=models.CharField(default='sem_usuario', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(default='sem_usuario', max_length=200),
            preserve_default=False,
        ),
    ]
